Repository Rejointech/Socio, pull requests merged in 2023-06, with the labels that each got.

#7 add CI workflows
  .github/workflows/CI.yml
  Cargo.toml
  crates/common_enums/src/lib.rs
  crates/common_enums/src/main.rs
  crates/common_utils/src/lib.rs
  crates/common_utils/src/main.rs
  crates/router/Cargo.toml
Labels: documentation, A-CI-CD, S-Waiting on Review

#10 feat: add issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: S-Waiting on Review

#11 feat(CI): add cargo workflows
  .github/workflows/CI.yml
  crates/common_enums/src/lib.rs
  crates/common_utils/src/lib.rs
Labels: A-CI-CD, S-Waiting on Review

#12 feat(actix): basic implementation of actix
  .github/workflows/CI.yml
  Cargo.toml
  crates/router/Cargo.toml
  crates/router/src/bin/router.rs
  crates/router/src/lib.rs
  crates/router/src/main.rs
  crates/router/src/routes.rs
  crates/router/src/routes/health.rs
Labels: P-High

#14 feat(router): Basic test implementations
  Cargo.toml
  README.md
  crates/router/Cargo.toml
  crates/router/src/lib.rs
  crates/router/tests/health.rs
Labels: S-Waiting on Review
